[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.100.0",
    "numpy>=1.20.0",
    "pydantic>=2.0.0",
    "scikit-learn>=1.1.0",
    "uvicorn[standard]>=0.20.0",
]
